# Generated by Django 4.2 on 2025-02-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cake_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cakeid', models.CharField(max_length=20)),
                ('cake_type', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='documents/')),
                ('cost_pe_kg', models.CharField(max_length=80)),
                ('duration', models.CharField(max_length=40)),
                ('flavors', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=20)),
                ('mobile_no', models.CharField(max_length=40)),
                ('email_id', models.CharField(max_length=80)),
                ('Address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='delivery_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=20)),
                ('customerid', models.CharField(max_length=50)),
                ('charges', models.CharField(max_length=40)),
                ('date', models.CharField(max_length=80)),
                ('time', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='order_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=20)),
                ('customerid', models.CharField(max_length=50)),
                ('cakeid', models.CharField(max_length=40)),
                ('booking_date', models.CharField(max_length=80)),
                ('total_weight', models.CharField(max_length=40)),
                ('cost', models.CharField(max_length=40)),
                ('Issue_date', models.CharField(max_length=40)),
                ('delivery_type', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='owner_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=40)),
                ('email_id', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='userreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=40)),
                ('mobile_no', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=80)),
            ],
        ),
    ]
