# Generated by Django 4.2 on 2025-04-18 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.CharField(max_length=20)),
                ('card_number', models.CharField(max_length=50)),
                ('card_holder_name', models.CharField(max_length=40)),
                ('expiry_date', models.CharField(max_length=80)),
                ('cvv_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='cake_details',
            name='category',
            field=models.CharField(default='All Cakes', max_length=100),
        ),
    ]
