# Generated by Django 4.2 on 2025-04-19 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0002_payment_cake_details_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake_details',
            name='category',
        ),
    ]
