# Generated by Django 4.2 on 2025-04-21 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0003_remove_cake_details_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='cvv_code',
            new_name='cvv_number',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
